# Generated by Django 2.2.2 on 2019-06-08 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='ratting',
            new_name='rating',
        ),
    ]
