# Generated by Django 2.2.2 on 2019-06-09 19:46

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190609_1824'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='movie',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='person',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='writer',
            new_name='writers',
        ),
    ]
